"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { api } from "../lib/api";

export default function CreateListingPage() {
  const [message, setMessage] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = new FormData(event.currentTarget); setMessage("Submitting listing..."); api("/api/listings", { method: "POST", body: JSON.stringify({ title: values.get("title"), area: values.get("area"), lga: values.get("lga"), address: values.get("address"), type: values.get("type"), beds: Number(values.get("beds")), baths: Number(values.get("baths")), rentPerYear: Number(values.get("rent")), cautionFee: Number(values.get("caution")) || 0, serviceCharge: Number(values.get("service")) || 0, landlordName: values.get("landlordName"), landlordPhone: values.get("phone"), landlordWhatsApp: values.get("whatsapp"), description: values.get("description"), amenities: [], images: [], documents: [] }) }).then(() => setMessage("Listing submitted for review.")).catch((reason: Error) => setMessage(reason.message)); };
  return <main className="min-h-screen bg-[#f7f4f0] px-5 py-8 font-manrope text-[#09182a] md:px-12"><header className="mx-auto flex max-w-3xl items-center justify-between"><Link href="/landlord-dashboard" className="font-bold text-[#a97e4b]">← Dashboard</Link><span className="text-sm font-extrabold">Create listing</span></header><form onSubmit={submit} className="mx-auto mt-12 grid max-w-3xl gap-5 rounded-2xl bg-white p-6 shadow-sm sm:p-10"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-[#a97e4b]">Property details</p><h1 className="mt-2 font-playfair text-4xl font-bold">List your property</h1></div><Field name="title" label="Listing title" placeholder="Modern 2-bedroom flat" /><div className="grid gap-5 sm:grid-cols-2"><Field name="area" label="Area" placeholder="Yaba" /><Field name="lga" label="LGA" placeholder="Lagos Mainland" /></div><Field name="address" label="Full address" placeholder="14 Herbert Macaulay Way" /><div className="grid gap-5 sm:grid-cols-3"><Field name="type" label="Property type" placeholder="2 Bedroom" /><Field name="beds" label="Bedrooms" type="number" placeholder="2" /><Field name="baths" label="Bathrooms" type="number" placeholder="2" /></div><div className="grid gap-5 sm:grid-cols-3"><Field name="rent" label="Annual rent" type="number" placeholder="800000" /><Field name="caution" label="Caution fee" type="number" placeholder="400000" /><Field name="service" label="Service charge" type="number" placeholder="100000" /></div><Field name="landlordName" label="Contact name" placeholder="Your full name" /><div className="grid gap-5 sm:grid-cols-2"><Field name="phone" label="Phone" placeholder="080..." /><Field name="whatsapp" label="WhatsApp" placeholder="234..." /></div><label className="grid gap-2 text-sm font-bold">Description<textarea name="description" required rows={5} className="rounded-lg border border-[#09182a20] p-3 font-medium outline-none" placeholder="Describe the property..." /></label><button className="rounded-lg bg-[#09182a] py-3 text-sm font-extrabold text-white" type="submit">Submit for review</button>{message && <p className="text-sm font-bold text-[#a97e4b]" role="status">{message}</p>}</form></main>;
}

function Field({ name, label, placeholder, type = "text" }: { name: string; label: string; placeholder: string; type?: string }) { return <label className="grid gap-2 text-sm font-bold">{label}<input name={name} type={type} placeholder={placeholder} required className="h-11 rounded-lg border border-[#09182a20] px-3 font-medium outline-none focus:border-[#a97e4b]" /></label>; }
